### ISSUE TITLE
'Expire Cache' does not seem to do anything for json content cache

### ISSUE THREAD

**Issue by georgy** [georgy/nexus-npm-repository-plugin#1]
Expected: After 'Expire Cache' is called on proxy repo I expect next request to hit remote resource and recreate local cache file.

Observed: After 'Expire Cache' content is served as is from local cache

**Comment by cstamas** [comment]
PR https://github.com/georgy/nexus-npm-repository-plugin/pull/10 now introduces the proper behaviour. Expire caches will expire not only the localstorage cache content (tarballs), but also the metadata service database too.
