### ISSUE TITLE
Nexus version 2.8.0-05

### ISSUE THREAD

**Issue by mcm2226** [georgy/nexus-npm-repository-plugin#2]
I have nexus version 2.8.0-05, and the plugin fails to start.  The only error in the logs is this:

The following plugins were processed:
... com.bolyuba.nexus.plugin:nexus-npm-repository-plugin:0.0.1 :: action=ACTIVATE result=BROKEN
       Reason: Problem installing: reference:file:/opt/scm/nexus-work/sonatype-work/nexus/plugin-repository/nexus-npm-repository-plugin-0.0.1/

Not much of an error to go on.  I tried it on nexus 2.7.2-03 and it worked fine.  Any idea what the problem might be?

Thanks,
-Matt

**Comment by georgy** [comment]
That is expected as I currently build plugin against 2.7.2-03. What functionality are you planning to use? Just proxy?

**Comment by mcm2226** [comment]
Yeah.  As it is now, everything seems to work perfectly as I need it.  The issue just being that our actual server is on a different version of nexus.

**Comment by mcm2226** [comment]
I didn't realized I had closed this, didn't mean to do that

**Comment by georgy** [comment]
I will keep it open if you do not mind :)
