### ISSUE TITLE
Compatibility with Nexus 2.9.1-02

### ISSUE THREAD

**Issue by pawelstep** [georgy/nexus-npm-repository-plugin#21]
Hello,

we want to use this plugin with Nexus 2.9.1-02 (at this moment doesn't work, probably because the Nexus base classes name changed).

Best regards,

P.

**Comment by marcellodesales** [comment]
Hi @pawelstep, look at https://issues.sonatype.org/browse/NEXUS-5852 for instructions on how to use the plugin... I Dockerized a server with it installed at https://registry.hub.docker.com/u/marcellodesales/nexus-npm-registry/.

Nexus OSS 2.10 version instead of 2.9.x
