### ISSUE TITLE
How to enable request caching? (ie why no 304 responses?)

### ISSUE THREAD

**Issue by phillipgreenii** [georgy/nexus-npm-repository-plugin#24]
Both nexus and NPM are new to me, so let me know if this is the wrong place to ask.  I noticed that I always received 200 responses.  (see below)  Is it a problem nexus or the plugin or my local configuration that causes 200 responses each time instead of 304s?  When using registery.npmjs.org, 304s happen more often than not because I am downloading the same things over and over.

```
npm http GET http://localhost:8081/nexus/content/groups/npmgroup/core-util-is
npm http GET http://localhost:8081/nexus/content/groups/npmgroup/isarray/0.0.1
npm http GET http://localhost:8081/nexus/content/groups/npmgroup/string_decoder
npm http 200 http://localhost:8081/nexus/content/groups/npmgroup/isarray/0.0.1
npm http 200 http://localhost:8081/nexus/content/groups/npmgroup/core-util-is
npm http 200 http://localhost:8081/nexus/content/groups/npmgroup/string_decoder
```

**Comment by georgy** [comment]
I would describe this as a feature request :). Let me get back to you on this one

**Comment by georgy** [comment]
This plugin is now a part of nexus-oss. You should raise an issue in that repo
